### PR TITLE
chore: update data for the 0.9 breaking change

### PR DESCRIPTION
**Pull request by IceTDrinker**

### CODE REVIEW

**Comment by nsarlin-zama** [comment]
There are some fixes to do in the README, in "usage" v0.1 should be changed to v0.3 (I forgot to do it for 0.2) and in "Adding a new tfhe-rs release", `data_0.6.rs` changed to `data_0.8.rs`

**Comment by IceTDrinker** [comment]
thanks will check those

**Review by nsarlin-zama — COMMENTED** [review]
This looks good to me overall !

Since the the `HlCiphertextList` test is not used anymore (it was the homogeneous lists of pre < 0.7). We could rename the `HlHeterogeneousCiphertextListTest` to `HlCiphertextList` since there is no more ambiguity. This would require to update the test on the corresponding PR.

**Review by nsarlin-zama — APPROVED** [review]
thanks !

**Pull request merged**
